image: docker/compose:latest

services:
  - name: docker:dind
    alias: localhost
variables:
  VERSION: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - package
#  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  before_script:
    - chmod +x gradlew && export GRADLE_USER_HOME=`pwd`/.gradle
  stage: build
  script:
    - apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
    - yarn install
    - apk add openjdk8
    - ./gradlew -Prelease.version=$VERSION final
    - ls

  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

docker-package:
  stage: package
#  tags: ["run03_docker"]
  script:
    - echo "Building docker image"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
