image: docker/compose:latest

services:
  - name: docker:dind
    alias: localhost

stages:
  - build
  - package
#  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


build:
  stage: build
  script:
    - apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
    - yarn install
    - apk add openjdk8
    - chmod +x ./gradlew
    - ./gradlew jar
    - echo "commit short $CI_COMMIT_SHORT_SHA"
    - echo "registry image $CI_REGISTRY_IMAGE"

  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

docker-package:
  stage: package
#  tags: ["run03_docker"]
  script:
    - echo "Building docker image"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  dependencies:
    - build
